#!/usr/bin/env bash

prefix="vcw_module_hkvb_streamsets__$1"
prefix="vcw_module_hkvb_streamsets__$1"

if [[ "vcw_module_hkvb_streamsets__streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_streamsets__streamsets_volume
fi
